name: Chrome Docker

on: # [push, workflow_dispatch]
  # - push
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Target ARC name used for `runs-on` in job'
        default: ubuntu-latest

jobs:
  # run Chrome inside a Docker container
  chrome:
    runs-on:
      - ${{ inputs.arc_name }}
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Chrome
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
