name: Chrome

# on: # [push, workflow_dispatch]
#   # - push
#   - workflow_dispatch:

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Target ARC name used for `runs-on` in job'
        default: ubuntu-latest

# jobs:
#   # test-connection-1:
#   #   runs-on:
#   #     - ${{ inputs.arc_name }}

jobs:
  chrome:
    runs-on:
      - ${{ inputs.arc_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Chrome
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
